### PR TITLE
Updating the version to 0.1.0.0 for release.

### PR DESCRIPTION
**Pull request by swernli**
@jterry75 @jstarks 
This also updates the appveyor build number, and cleans up the appveyor build a bit.

### CODE REVIEW

**Comment by jstarks** [comment]
Also get project.json

**Comment by jterry75** [comment]
That is far to many places to update the version each time and not miss them. How can we simplify this?

**Comment by jstarks** [comment]
Well, only the appveyor update is strictly necessary since it overwrites the version everywhere else. But for local builds, we don't currently have a mechanism.

If you can get rid of the nuspec and use dotnet pack, that would eliminate one update. And maybe we could have appveyor pull the version prefix from the project.json and just append the build number; that would eliminate another. Unfortunately the psd1 and the nuget version have to remain in sync, though.

**Comment by jstarks** [comment]
(The assembly version doesn't really matter since it's never GACed, but it's nice to have it in sync.)

**Pull request merged**
