### PR TITLE
Creates the cross-platform nupkg.

### PR DESCRIPTION
**Pull request by jterry75**
1. Refactors the *.nuspec to properly include both versions of the PS
Module in the same package.
2. Fixes the TAR package for net46 so we dont copy facade dll's for no
reason.

### CODE REVIEW

**Comment by jterry75** [comment]
Well that was quick. AppVeyor only has PS 5.0.10586.117 and the cross plat multipackage is only supported in 5.1.14300.1000.

**Comment by jterry75** [comment]
We are going to have to publish two feeds. This will never work for downlevel clients.

**Comment by swernli** [comment]
It might be possible to update powershell on the Appveyor instance... But only if we can find a way to get that on there without a reboot.

**Comment by swernli** [comment]
Oh, never mind. Just saw your email: this won't work because of customers who have 5.0. As long as we still want to target them, we are stuck.

**Pull request closed without merging**
