### PR TITLE
Fixing Docker PowerShell on NanoServer

### PR DESCRIPTION
**Pull request by jterry75**
Resolves: #157

### CODE REVIEW

**Comment by jterry75** [comment]
Don't merge until I get a chance to pull this on Nano and check. The local builds are fine but the AppVeyor might give us grief.

**Comment by swernli** [comment]
LGTM?

**Comment by rs38** [comment]
`Update-Module Docker`

_Cannot convert null to type "System.DateTime".
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:6843 char:17
+                 $InstalledDate = $null
+                 ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : MetadataError: (:) [], ArgumentTransformationMetadataException
    + FullyQualifiedErrorId : RuntimeException_

????

**Comment by jterry75** [comment]
What build of nano are you on by chance? Also what is the version of:

```PowerShell
Get-Module PackageManagement
Get-Module PowerShellGet
Get-PackageProvider NuGet
```

**Pull request merged**
