### PR TITLE
Using Publish-Module instead of nuget pack

### PR DESCRIPTION
**Pull request by swernli**
This is meant to resolve https://github.com/Microsoft/Docker-PowerShell/issues/145, using the powershell cmdlets for creating the nupkg instead of the nuget cmdline tool itself.

@jterry75 @jstarks @jianyunt @bmanikm

### CODE REVIEW

**Comment by swernli** [comment]
@jterry75 This is finally ready for review and merge...

**Comment by bmanikm** [comment]
:shipit:

**Comment by jianyunt** [comment]
LGTM

**Comment by jterry75** [comment]
Wahoo! LGTM!

**Pull request merged**
